Algoritmo "pag25exB"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Sofia
// Data atual  : 18/09/2025
Var
// Seção de Declarações das variáveis 
   c, f : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a temperatura a ser convertida (°F > °C): ")
    leia(f)

    c <- (f-32)*(5/9)

    Escreval(f, "°F é ", c, " °C")

Fimalgoritmo