Algoritmo "pag25exL"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Santos
// Descrição   : Soma dos quadrados de três valores
// Autor(a)    : Sofia
// Data atual  : 29/09/2025
Var
// Seção de Declarações das variáveis
   a, b, c, resultado : real

Inicio
// Seção de Comandos
   escreval("Digite três valores:")
   leia(a)
   leia(b)
   leia(c)

   resultado <- (a^2) + (b^2) + (c^2)

   escreva("A soma dos quadrados é: ", resultado:0:2)
Fimalgoritmo