Algoritmo "pag25exA"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : sofia
// Data atual  : 18/09/2025
Var
// Seção de Declarações das variáveis 
   c, f : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva("Digite a temperatura a ser convertida (°C > °F): ")
    leia(c)
    
    f <- ((9*c)+160) /5
    
    Escreval(c, "°C é ", f, " °F")

Fimalgoritmo