Algoritmo "impares"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Santos
// Descrição   : Mostra números ímpares de 0 a 20
// Autor(a)    : Sofia
// Data atual  : 26/09/2025
Var
// Seção de Declarações das variáveis
   i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 0
   enquanto i <= 20 faca
      se i mod 2 <> 0 entao
         escreval(i)
      fimse
      i <- i + 1
   fimenquanto
   
Fimalgoritmo