Algoritmo "somacem"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Santos
// Descrição   : Soma dos 100 primeiros números inteiros
// Autor(a)    : Sofia
// Data atual  : 26/09/2025
Var
// Seção de Declarações das variáveis
   i, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 1
   soma <- 0
   enquanto i <= 100 faca
      soma <- soma + i
      i <- i + 1
   fimenquanto
   escreval("Soma total = ", soma)
   
Fimalgoritmo