Algoritmo "pag41exK"
// Disciplina   : Lógica de Programação
// Professor   : Jailson Santos
// Descrição   : Apresenta valor se não for maior que 3
// Autor(a)    : Sofia
// Data atual  : 26/09/2025
Var
// Seção de Declarações das variáveis
   valor : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite um valor inteiro:")
   leia(valor)

   se valor <= 3 entao
      escreval("Valor informado: ", valor)
   fimse

Fimalgoritmo