Algoritmo "pag66exC"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Santos
// Descrição    : Somar os cem primeiros números inteiros (1 a 100)
// Autor(a)     : Sofia
// Data atual   : 29/09/2025

Var
// Seção de Declarações das variáveis
   i, soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   soma <- 0
   para i de 1 ate 100 faca
      soma <- soma + i
   fimpara
   escreval("Soma dos 100 primeiros números: ", soma)
Fimalgoritmo