Algoritmo "pag66exE"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Santos
// Descrição    : Apresentar todos os números ímpares de 0 a 20
// Autor(a)     : Sofia
// Data atual   : 29/09/2025

Var
// Seção de Declarações das variáveis
   i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 0 ate 20 faca
      se (i % 2 <> 0) entao
         escreval(i)
      fimse
   fimpara
Fimalgoritmo