Algoritmo "pag66exF"
/ Disciplina   : Lógica de Programação
// Professor    : Jailson Santos
// Descrição    : Apresentar todos os números divisíveis por 4 menores que 200
// Autor(a)     : Sofia
// Data atual   : 29/09/2025

Var
   // Seção de Declarações das variáveis
   i : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 1 ate 199 faca
      se (i % 4 = 0) entao
         escreval(i)
      fimse
   fimpara
Fimalgoritmo