Algoritmo "pag66exA"
// Disciplina   : Lógica de Programação
// Professor    : Jailson Santos
// Descrição    : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)     : Sofia
// Data atual   : 29/09/2025

Var
// Seção de Declarações das variáveis
   i, quadrado : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 15 ate 200 faca
      quadrado <- i * i
      escreval("Número: ", i, "  Quadrado: ", quadrado)
   fimpara
Fimalgoritmo
